### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.IAuthenticatorSettings
  commentId: T:Okta.Sdk.IAuthenticatorSettings
  id: IAuthenticatorSettings
  parent: Okta.Sdk
  children:
  - Okta.Sdk.IAuthenticatorSettings.AllowedFor
  - Okta.Sdk.IAuthenticatorSettings.AppInstanceId
  - Okta.Sdk.IAuthenticatorSettings.ChannelBinding
  - Okta.Sdk.IAuthenticatorSettings.Compliance
  - Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes
  - Okta.Sdk.IAuthenticatorSettings.UserVerification
  langs:
  - csharp
  - vb
  name: IAuthenticatorSettings
  nameWithType: IAuthenticatorSettings
  fullName: Okta.Sdk.IAuthenticatorSettings
  type: Interface
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: IAuthenticatorSettings
    path: ../src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: Represents a AuthenticatorSettings resource in the Okta API.
  example: []
  syntax:
    content: 'public interface IAuthenticatorSettings : IResource'
    content.vb: >-
      Public Interface IAuthenticatorSettings

          Inherits IResource
  inheritedMembers:
  - Okta.Sdk.IResource.Item(System.String)
  - Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  - Okta.Sdk.IResource.GetData
  - Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  - Okta.Sdk.IResource.GetProperty``1(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Okta.Sdk.IAuthenticatorSettings.AllowedFor
  commentId: P:Okta.Sdk.IAuthenticatorSettings.AllowedFor
  id: AllowedFor
  parent: Okta.Sdk.IAuthenticatorSettings
  langs:
  - csharp
  - vb
  name: AllowedFor
  nameWithType: IAuthenticatorSettings.AllowedFor
  fullName: Okta.Sdk.IAuthenticatorSettings.AllowedFor
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: AllowedFor
    path: ../src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
    startLine: 17
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: AllowedForEnum AllowedFor { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.AllowedForEnum
    content.vb: Property AllowedFor As AllowedForEnum
  overload: Okta.Sdk.IAuthenticatorSettings.AllowedFor*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IAuthenticatorSettings.AppInstanceId
  commentId: P:Okta.Sdk.IAuthenticatorSettings.AppInstanceId
  id: AppInstanceId
  parent: Okta.Sdk.IAuthenticatorSettings
  langs:
  - csharp
  - vb
  name: AppInstanceId
  nameWithType: IAuthenticatorSettings.AppInstanceId
  fullName: Okta.Sdk.IAuthenticatorSettings.AppInstanceId
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: AppInstanceId
    path: ../src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
    startLine: 19
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: string AppInstanceId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property AppInstanceId As String
  overload: Okta.Sdk.IAuthenticatorSettings.AppInstanceId*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IAuthenticatorSettings.ChannelBinding
  commentId: P:Okta.Sdk.IAuthenticatorSettings.ChannelBinding
  id: ChannelBinding
  parent: Okta.Sdk.IAuthenticatorSettings
  langs:
  - csharp
  - vb
  name: ChannelBinding
  nameWithType: IAuthenticatorSettings.ChannelBinding
  fullName: Okta.Sdk.IAuthenticatorSettings.ChannelBinding
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: ChannelBinding
    path: ../src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
    startLine: 21
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: IChannelBinding ChannelBinding { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.IChannelBinding
    content.vb: Property ChannelBinding As IChannelBinding
  overload: Okta.Sdk.IAuthenticatorSettings.ChannelBinding*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IAuthenticatorSettings.Compliance
  commentId: P:Okta.Sdk.IAuthenticatorSettings.Compliance
  id: Compliance
  parent: Okta.Sdk.IAuthenticatorSettings
  langs:
  - csharp
  - vb
  name: Compliance
  nameWithType: IAuthenticatorSettings.Compliance
  fullName: Okta.Sdk.IAuthenticatorSettings.Compliance
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Compliance
    path: ../src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
    startLine: 23
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: ICompliance Compliance { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.ICompliance
    content.vb: Property Compliance As ICompliance
  overload: Okta.Sdk.IAuthenticatorSettings.Compliance*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes
  commentId: P:Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes
  id: TokenLifetimeInMinutes
  parent: Okta.Sdk.IAuthenticatorSettings
  langs:
  - csharp
  - vb
  name: TokenLifetimeInMinutes
  nameWithType: IAuthenticatorSettings.TokenLifetimeInMinutes
  fullName: Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: TokenLifetimeInMinutes
    path: ../src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
    startLine: 25
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: int? TokenLifetimeInMinutes { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Property TokenLifetimeInMinutes As Integer?
  overload: Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IAuthenticatorSettings.UserVerification
  commentId: P:Okta.Sdk.IAuthenticatorSettings.UserVerification
  id: UserVerification
  parent: Okta.Sdk.IAuthenticatorSettings
  langs:
  - csharp
  - vb
  name: UserVerification
  nameWithType: IAuthenticatorSettings.UserVerification
  fullName: Okta.Sdk.IAuthenticatorSettings.UserVerification
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: UserVerification
    path: ../src/Okta.Sdk/Generated/IAuthenticatorSettings.Generated.cs
    startLine: 27
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: UserVerificationEnum UserVerification { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.UserVerificationEnum
    content.vb: Property UserVerification As UserVerificationEnum
  overload: Okta.Sdk.IAuthenticatorSettings.UserVerification*
  modifiers.csharp:
  - get
  - set
references:
- uid: Okta.Sdk
  commentId: N:Okta.Sdk
  name: Okta.Sdk
  nameWithType: Okta.Sdk
  fullName: Okta.Sdk
- uid: Okta.Sdk.IResource.Item(System.String)
  commentId: P:Okta.Sdk.IResource.Item(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: Item[String]
  nameWithType: IResource.Item[String]
  fullName: Okta.Sdk.IResource.Item[System.String]
  nameWithType.vb: IResource.Item(String)
  fullName.vb: Okta.Sdk.IResource.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetArrayProperty<T>(String)
  nameWithType: IResource.GetArrayProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetArrayProperty<T>(System.String)
  nameWithType.vb: IResource.GetArrayProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetArrayProperty(Of T)(System.String)
  name.vb: GetArrayProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty<T>
    nameWithType: IResource.GetArrayProperty<T>
    fullName: Okta.Sdk.IResource.GetArrayProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty(Of T)
    nameWithType: IResource.GetArrayProperty(Of T)
    fullName: Okta.Sdk.IResource.GetArrayProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetData
  commentId: M:Okta.Sdk.IResource.GetData
  parent: Okta.Sdk.IResource
  name: GetData()
  nameWithType: IResource.GetData()
  fullName: Okta.Sdk.IResource.GetData()
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  commentId: M:Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: SetProperty(String, Object)
  nameWithType: IResource.SetProperty(String, Object)
  fullName: Okta.Sdk.IResource.SetProperty(System.String, System.Object)
  spec.csharp:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetProperty<T>(String)
  nameWithType: IResource.GetProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetProperty<T>(System.String)
  nameWithType.vb: IResource.GetProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetProperty(Of T)(System.String)
  name.vb: GetProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty<T>
    nameWithType: IResource.GetProperty<T>
    fullName: Okta.Sdk.IResource.GetProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty(Of T)
    nameWithType: IResource.GetProperty(Of T)
    fullName: Okta.Sdk.IResource.GetProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource
  commentId: T:Okta.Sdk.IResource
  parent: Okta.Sdk
  name: IResource
  nameWithType: IResource
  fullName: Okta.Sdk.IResource
- uid: Okta.Sdk.IAuthenticatorSettings.AllowedFor*
  commentId: Overload:Okta.Sdk.IAuthenticatorSettings.AllowedFor
  name: AllowedFor
  nameWithType: IAuthenticatorSettings.AllowedFor
  fullName: Okta.Sdk.IAuthenticatorSettings.AllowedFor
- uid: Okta.Sdk.AllowedForEnum
  commentId: T:Okta.Sdk.AllowedForEnum
  parent: Okta.Sdk
  name: AllowedForEnum
  nameWithType: AllowedForEnum
  fullName: Okta.Sdk.AllowedForEnum
- uid: Okta.Sdk.IAuthenticatorSettings.AppInstanceId*
  commentId: Overload:Okta.Sdk.IAuthenticatorSettings.AppInstanceId
  name: AppInstanceId
  nameWithType: IAuthenticatorSettings.AppInstanceId
  fullName: Okta.Sdk.IAuthenticatorSettings.AppInstanceId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Okta.Sdk.IAuthenticatorSettings.ChannelBinding*
  commentId: Overload:Okta.Sdk.IAuthenticatorSettings.ChannelBinding
  name: ChannelBinding
  nameWithType: IAuthenticatorSettings.ChannelBinding
  fullName: Okta.Sdk.IAuthenticatorSettings.ChannelBinding
- uid: Okta.Sdk.IChannelBinding
  commentId: T:Okta.Sdk.IChannelBinding
  parent: Okta.Sdk
  name: IChannelBinding
  nameWithType: IChannelBinding
  fullName: Okta.Sdk.IChannelBinding
- uid: Okta.Sdk.IAuthenticatorSettings.Compliance*
  commentId: Overload:Okta.Sdk.IAuthenticatorSettings.Compliance
  name: Compliance
  nameWithType: IAuthenticatorSettings.Compliance
  fullName: Okta.Sdk.IAuthenticatorSettings.Compliance
- uid: Okta.Sdk.ICompliance
  commentId: T:Okta.Sdk.ICompliance
  parent: Okta.Sdk
  name: ICompliance
  nameWithType: ICompliance
  fullName: Okta.Sdk.ICompliance
- uid: Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes*
  commentId: Overload:Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes
  name: TokenLifetimeInMinutes
  nameWithType: IAuthenticatorSettings.TokenLifetimeInMinutes
  fullName: Okta.Sdk.IAuthenticatorSettings.TokenLifetimeInMinutes
- uid: System.Nullable{System.Int32}
  commentId: T:System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int32>
  nameWithType: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  nameWithType.vb: Nullable(Of Int32)
  fullName.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IAuthenticatorSettings.UserVerification*
  commentId: Overload:Okta.Sdk.IAuthenticatorSettings.UserVerification
  name: UserVerification
  nameWithType: IAuthenticatorSettings.UserVerification
  fullName: Okta.Sdk.IAuthenticatorSettings.UserVerification
- uid: Okta.Sdk.UserVerificationEnum
  commentId: T:Okta.Sdk.UserVerificationEnum
  parent: Okta.Sdk
  name: UserVerificationEnum
  nameWithType: UserVerificationEnum
  fullName: Okta.Sdk.UserVerificationEnum
