### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.IBasicApplicationSettings
  commentId: T:Okta.Sdk.IBasicApplicationSettings
  id: IBasicApplicationSettings
  parent: Okta.Sdk
  children:
  - Okta.Sdk.IBasicApplicationSettings.App
  langs:
  - csharp
  - vb
  name: IBasicApplicationSettings
  nameWithType: IBasicApplicationSettings
  fullName: Okta.Sdk.IBasicApplicationSettings
  type: Interface
  source:
    remote:
      path: src/Okta.Sdk/Generated/IBasicApplicationSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: IBasicApplicationSettings
    path: ../src/Okta.Sdk/Generated/IBasicApplicationSettings.Generated.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: Represents a BasicApplicationSettings resource in the Okta API.
  example: []
  syntax:
    content: 'public interface IBasicApplicationSettings : IApplicationSettings, IResource'
    content.vb: >-
      Public Interface IBasicApplicationSettings

          Inherits IApplicationSettings
  inheritedMembers:
  - Okta.Sdk.IApplicationSettings.ImplicitAssignment
  - Okta.Sdk.IApplicationSettings.InlineHookId
  - Okta.Sdk.IApplicationSettings.Notes
  - Okta.Sdk.IApplicationSettings.Notifications
  - Okta.Sdk.IResource.Item(System.String)
  - Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  - Okta.Sdk.IResource.GetData
  - Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  - Okta.Sdk.IResource.GetProperty``1(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Okta.Sdk.IBasicApplicationSettings.App
  commentId: P:Okta.Sdk.IBasicApplicationSettings.App
  id: App
  parent: Okta.Sdk.IBasicApplicationSettings
  langs:
  - csharp
  - vb
  name: App
  nameWithType: IBasicApplicationSettings.App
  fullName: Okta.Sdk.IBasicApplicationSettings.App
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IBasicApplicationSettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: App
    path: ../src/Okta.Sdk/Generated/IBasicApplicationSettings.Generated.cs
    startLine: 17
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: IBasicApplicationSettingsApplication App { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.IBasicApplicationSettingsApplication
    content.vb: Property App As IBasicApplicationSettingsApplication
  overload: Okta.Sdk.IBasicApplicationSettings.App*
  modifiers.csharp:
  - get
  - set
references:
- uid: Okta.Sdk
  commentId: N:Okta.Sdk
  name: Okta.Sdk
  nameWithType: Okta.Sdk
  fullName: Okta.Sdk
- uid: Okta.Sdk.IApplicationSettings.ImplicitAssignment
  commentId: P:Okta.Sdk.IApplicationSettings.ImplicitAssignment
  parent: Okta.Sdk.IApplicationSettings
  name: ImplicitAssignment
  nameWithType: IApplicationSettings.ImplicitAssignment
  fullName: Okta.Sdk.IApplicationSettings.ImplicitAssignment
- uid: Okta.Sdk.IApplicationSettings.InlineHookId
  commentId: P:Okta.Sdk.IApplicationSettings.InlineHookId
  parent: Okta.Sdk.IApplicationSettings
  name: InlineHookId
  nameWithType: IApplicationSettings.InlineHookId
  fullName: Okta.Sdk.IApplicationSettings.InlineHookId
- uid: Okta.Sdk.IApplicationSettings.Notes
  commentId: P:Okta.Sdk.IApplicationSettings.Notes
  parent: Okta.Sdk.IApplicationSettings
  name: Notes
  nameWithType: IApplicationSettings.Notes
  fullName: Okta.Sdk.IApplicationSettings.Notes
- uid: Okta.Sdk.IApplicationSettings.Notifications
  commentId: P:Okta.Sdk.IApplicationSettings.Notifications
  parent: Okta.Sdk.IApplicationSettings
  name: Notifications
  nameWithType: IApplicationSettings.Notifications
  fullName: Okta.Sdk.IApplicationSettings.Notifications
- uid: Okta.Sdk.IResource.Item(System.String)
  commentId: P:Okta.Sdk.IResource.Item(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: Item[String]
  nameWithType: IResource.Item[String]
  fullName: Okta.Sdk.IResource.Item[System.String]
  nameWithType.vb: IResource.Item(String)
  fullName.vb: Okta.Sdk.IResource.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetArrayProperty<T>(String)
  nameWithType: IResource.GetArrayProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetArrayProperty<T>(System.String)
  nameWithType.vb: IResource.GetArrayProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetArrayProperty(Of T)(System.String)
  name.vb: GetArrayProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty<T>
    nameWithType: IResource.GetArrayProperty<T>
    fullName: Okta.Sdk.IResource.GetArrayProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty(Of T)
    nameWithType: IResource.GetArrayProperty(Of T)
    fullName: Okta.Sdk.IResource.GetArrayProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetData
  commentId: M:Okta.Sdk.IResource.GetData
  parent: Okta.Sdk.IResource
  name: GetData()
  nameWithType: IResource.GetData()
  fullName: Okta.Sdk.IResource.GetData()
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  commentId: M:Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: SetProperty(String, Object)
  nameWithType: IResource.SetProperty(String, Object)
  fullName: Okta.Sdk.IResource.SetProperty(System.String, System.Object)
  spec.csharp:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetProperty<T>(String)
  nameWithType: IResource.GetProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetProperty<T>(System.String)
  nameWithType.vb: IResource.GetProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetProperty(Of T)(System.String)
  name.vb: GetProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty<T>
    nameWithType: IResource.GetProperty<T>
    fullName: Okta.Sdk.IResource.GetProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty(Of T)
    nameWithType: IResource.GetProperty(Of T)
    fullName: Okta.Sdk.IResource.GetProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IApplicationSettings
  commentId: T:Okta.Sdk.IApplicationSettings
  parent: Okta.Sdk
  name: IApplicationSettings
  nameWithType: IApplicationSettings
  fullName: Okta.Sdk.IApplicationSettings
- uid: Okta.Sdk.IResource
  commentId: T:Okta.Sdk.IResource
  parent: Okta.Sdk
  name: IResource
  nameWithType: IResource
  fullName: Okta.Sdk.IResource
- uid: Okta.Sdk.IBasicApplicationSettings.App*
  commentId: Overload:Okta.Sdk.IBasicApplicationSettings.App
  name: App
  nameWithType: IBasicApplicationSettings.App
  fullName: Okta.Sdk.IBasicApplicationSettings.App
- uid: Okta.Sdk.IBasicApplicationSettingsApplication
  commentId: T:Okta.Sdk.IBasicApplicationSettingsApplication
  parent: Okta.Sdk
  name: IBasicApplicationSettingsApplication
  nameWithType: IBasicApplicationSettingsApplication
  fullName: Okta.Sdk.IBasicApplicationSettingsApplication
