### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.CreateSwaApplicationOptions
  commentId: T:Okta.Sdk.CreateSwaApplicationOptions
  id: CreateSwaApplicationOptions
  parent: Okta.Sdk
  children:
  - Okta.Sdk.CreateSwaApplicationOptions.Activate
  - Okta.Sdk.CreateSwaApplicationOptions.ButtonField
  - Okta.Sdk.CreateSwaApplicationOptions.Label
  - Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex
  - Okta.Sdk.CreateSwaApplicationOptions.PasswordField
  - Okta.Sdk.CreateSwaApplicationOptions.Url
  - Okta.Sdk.CreateSwaApplicationOptions.UsernameField
  langs:
  - csharp
  - vb
  name: CreateSwaApplicationOptions
  nameWithType: CreateSwaApplicationOptions
  fullName: Okta.Sdk.CreateSwaApplicationOptions
  type: Class
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: CreateSwaApplicationOptions
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 10
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nHelper class for a SWA application settings\n"
  example: []
  syntax:
    content: public sealed class CreateSwaApplicationOptions
    content.vb: Public NotInheritable Class CreateSwaApplicationOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Okta.Sdk.CreateSwaApplicationOptions.Label
  commentId: P:Okta.Sdk.CreateSwaApplicationOptions.Label
  id: Label
  parent: Okta.Sdk.CreateSwaApplicationOptions
  langs:
  - csharp
  - vb
  name: Label
  nameWithType: CreateSwaApplicationOptions.Label
  fullName: Okta.Sdk.CreateSwaApplicationOptions.Label
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Label
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nGets or sets a label\n"
  example: []
  syntax:
    content: public string Label { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Label As String
  overload: Okta.Sdk.CreateSwaApplicationOptions.Label*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Okta.Sdk.CreateSwaApplicationOptions.ButtonField
  commentId: P:Okta.Sdk.CreateSwaApplicationOptions.ButtonField
  id: ButtonField
  parent: Okta.Sdk.CreateSwaApplicationOptions
  langs:
  - csharp
  - vb
  name: ButtonField
  nameWithType: CreateSwaApplicationOptions.ButtonField
  fullName: Okta.Sdk.CreateSwaApplicationOptions.ButtonField
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: ButtonField
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 20
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nGets or sets a button field\n"
  example: []
  syntax:
    content: public string ButtonField { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ButtonField As String
  overload: Okta.Sdk.CreateSwaApplicationOptions.ButtonField*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Okta.Sdk.CreateSwaApplicationOptions.PasswordField
  commentId: P:Okta.Sdk.CreateSwaApplicationOptions.PasswordField
  id: PasswordField
  parent: Okta.Sdk.CreateSwaApplicationOptions
  langs:
  - csharp
  - vb
  name: PasswordField
  nameWithType: CreateSwaApplicationOptions.PasswordField
  fullName: Okta.Sdk.CreateSwaApplicationOptions.PasswordField
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: PasswordField
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 25
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nGets or sets a password field\n"
  example: []
  syntax:
    content: public string PasswordField { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property PasswordField As String
  overload: Okta.Sdk.CreateSwaApplicationOptions.PasswordField*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Okta.Sdk.CreateSwaApplicationOptions.UsernameField
  commentId: P:Okta.Sdk.CreateSwaApplicationOptions.UsernameField
  id: UsernameField
  parent: Okta.Sdk.CreateSwaApplicationOptions
  langs:
  - csharp
  - vb
  name: UsernameField
  nameWithType: CreateSwaApplicationOptions.UsernameField
  fullName: Okta.Sdk.CreateSwaApplicationOptions.UsernameField
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: UsernameField
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 30
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nGets or sets a username field\n"
  example: []
  syntax:
    content: public string UsernameField { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UsernameField As String
  overload: Okta.Sdk.CreateSwaApplicationOptions.UsernameField*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Okta.Sdk.CreateSwaApplicationOptions.Url
  commentId: P:Okta.Sdk.CreateSwaApplicationOptions.Url
  id: Url
  parent: Okta.Sdk.CreateSwaApplicationOptions
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: CreateSwaApplicationOptions.Url
  fullName: Okta.Sdk.CreateSwaApplicationOptions.Url
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Url
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 35
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nGets or sets an url\n"
  example: []
  syntax:
    content: public string Url { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Url As String
  overload: Okta.Sdk.CreateSwaApplicationOptions.Url*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex
  commentId: P:Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex
  id: LoginUrlRegex
  parent: Okta.Sdk.CreateSwaApplicationOptions
  langs:
  - csharp
  - vb
  name: LoginUrlRegex
  nameWithType: CreateSwaApplicationOptions.LoginUrlRegex
  fullName: Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: LoginUrlRegex
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 40
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nGets or sets a login url regex\n"
  example: []
  syntax:
    content: public string LoginUrlRegex { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LoginUrlRegex As String
  overload: Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Okta.Sdk.CreateSwaApplicationOptions.Activate
  commentId: P:Okta.Sdk.CreateSwaApplicationOptions.Activate
  id: Activate
  parent: Okta.Sdk.CreateSwaApplicationOptions
  langs:
  - csharp
  - vb
  name: Activate
  nameWithType: CreateSwaApplicationOptions.Activate
  fullName: Okta.Sdk.CreateSwaApplicationOptions.Activate
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/CreateSwaApplicationOptions.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Activate
    path: ../src/Okta.Sdk/CreateSwaApplicationOptions.cs
    startLine: 45
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: "\nGets or sets an activate flag value\n"
  example: []
  syntax:
    content: public bool Activate { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Activate As Boolean
  overload: Okta.Sdk.CreateSwaApplicationOptions.Activate*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Okta.Sdk
  commentId: N:Okta.Sdk
  name: Okta.Sdk
  nameWithType: Okta.Sdk
  fullName: Okta.Sdk
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Okta.Sdk.CreateSwaApplicationOptions.Label*
  commentId: Overload:Okta.Sdk.CreateSwaApplicationOptions.Label
  name: Label
  nameWithType: CreateSwaApplicationOptions.Label
  fullName: Okta.Sdk.CreateSwaApplicationOptions.Label
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Okta.Sdk.CreateSwaApplicationOptions.ButtonField*
  commentId: Overload:Okta.Sdk.CreateSwaApplicationOptions.ButtonField
  name: ButtonField
  nameWithType: CreateSwaApplicationOptions.ButtonField
  fullName: Okta.Sdk.CreateSwaApplicationOptions.ButtonField
- uid: Okta.Sdk.CreateSwaApplicationOptions.PasswordField*
  commentId: Overload:Okta.Sdk.CreateSwaApplicationOptions.PasswordField
  name: PasswordField
  nameWithType: CreateSwaApplicationOptions.PasswordField
  fullName: Okta.Sdk.CreateSwaApplicationOptions.PasswordField
- uid: Okta.Sdk.CreateSwaApplicationOptions.UsernameField*
  commentId: Overload:Okta.Sdk.CreateSwaApplicationOptions.UsernameField
  name: UsernameField
  nameWithType: CreateSwaApplicationOptions.UsernameField
  fullName: Okta.Sdk.CreateSwaApplicationOptions.UsernameField
- uid: Okta.Sdk.CreateSwaApplicationOptions.Url*
  commentId: Overload:Okta.Sdk.CreateSwaApplicationOptions.Url
  name: Url
  nameWithType: CreateSwaApplicationOptions.Url
  fullName: Okta.Sdk.CreateSwaApplicationOptions.Url
- uid: Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex*
  commentId: Overload:Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex
  name: LoginUrlRegex
  nameWithType: CreateSwaApplicationOptions.LoginUrlRegex
  fullName: Okta.Sdk.CreateSwaApplicationOptions.LoginUrlRegex
- uid: Okta.Sdk.CreateSwaApplicationOptions.Activate*
  commentId: Overload:Okta.Sdk.CreateSwaApplicationOptions.Activate
  name: Activate
  nameWithType: CreateSwaApplicationOptions.Activate
  fullName: Okta.Sdk.CreateSwaApplicationOptions.Activate
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
