### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.IApplicationCredentialsSigning
  commentId: T:Okta.Sdk.IApplicationCredentialsSigning
  id: IApplicationCredentialsSigning
  parent: Okta.Sdk
  children:
  - Okta.Sdk.IApplicationCredentialsSigning.Kid
  - Okta.Sdk.IApplicationCredentialsSigning.LastRotated
  - Okta.Sdk.IApplicationCredentialsSigning.NextRotation
  - Okta.Sdk.IApplicationCredentialsSigning.RotationMode
  - Okta.Sdk.IApplicationCredentialsSigning.Use
  langs:
  - csharp
  - vb
  name: IApplicationCredentialsSigning
  nameWithType: IApplicationCredentialsSigning
  fullName: Okta.Sdk.IApplicationCredentialsSigning
  type: Interface
  source:
    remote:
      path: src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: IApplicationCredentialsSigning
    path: ../src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: Represents a ApplicationCredentialsSigning resource in the Okta API.
  example: []
  syntax:
    content: 'public interface IApplicationCredentialsSigning : IResource'
    content.vb: >-
      Public Interface IApplicationCredentialsSigning

          Inherits IResource
  inheritedMembers:
  - Okta.Sdk.IResource.Item(System.String)
  - Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  - Okta.Sdk.IResource.GetData
  - Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  - Okta.Sdk.IResource.GetProperty``1(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Okta.Sdk.IApplicationCredentialsSigning.Kid
  commentId: P:Okta.Sdk.IApplicationCredentialsSigning.Kid
  id: Kid
  parent: Okta.Sdk.IApplicationCredentialsSigning
  langs:
  - csharp
  - vb
  name: Kid
  nameWithType: IApplicationCredentialsSigning.Kid
  fullName: Okta.Sdk.IApplicationCredentialsSigning.Kid
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Kid
    path: ../src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
    startLine: 17
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: string Kid { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Kid As String
  overload: Okta.Sdk.IApplicationCredentialsSigning.Kid*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IApplicationCredentialsSigning.LastRotated
  commentId: P:Okta.Sdk.IApplicationCredentialsSigning.LastRotated
  id: LastRotated
  parent: Okta.Sdk.IApplicationCredentialsSigning
  langs:
  - csharp
  - vb
  name: LastRotated
  nameWithType: IApplicationCredentialsSigning.LastRotated
  fullName: Okta.Sdk.IApplicationCredentialsSigning.LastRotated
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: LastRotated
    path: ../src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
    startLine: 19
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: DateTimeOffset? LastRotated { get; }
    parameters: []
    return:
      type: System.Nullable{System.DateTimeOffset}
    content.vb: ReadOnly Property LastRotated As DateTimeOffset?
  overload: Okta.Sdk.IApplicationCredentialsSigning.LastRotated*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Okta.Sdk.IApplicationCredentialsSigning.NextRotation
  commentId: P:Okta.Sdk.IApplicationCredentialsSigning.NextRotation
  id: NextRotation
  parent: Okta.Sdk.IApplicationCredentialsSigning
  langs:
  - csharp
  - vb
  name: NextRotation
  nameWithType: IApplicationCredentialsSigning.NextRotation
  fullName: Okta.Sdk.IApplicationCredentialsSigning.NextRotation
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: NextRotation
    path: ../src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
    startLine: 21
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: DateTimeOffset? NextRotation { get; }
    parameters: []
    return:
      type: System.Nullable{System.DateTimeOffset}
    content.vb: ReadOnly Property NextRotation As DateTimeOffset?
  overload: Okta.Sdk.IApplicationCredentialsSigning.NextRotation*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Okta.Sdk.IApplicationCredentialsSigning.RotationMode
  commentId: P:Okta.Sdk.IApplicationCredentialsSigning.RotationMode
  id: RotationMode
  parent: Okta.Sdk.IApplicationCredentialsSigning
  langs:
  - csharp
  - vb
  name: RotationMode
  nameWithType: IApplicationCredentialsSigning.RotationMode
  fullName: Okta.Sdk.IApplicationCredentialsSigning.RotationMode
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: RotationMode
    path: ../src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
    startLine: 23
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: string RotationMode { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property RotationMode As String
  overload: Okta.Sdk.IApplicationCredentialsSigning.RotationMode*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IApplicationCredentialsSigning.Use
  commentId: P:Okta.Sdk.IApplicationCredentialsSigning.Use
  id: Use
  parent: Okta.Sdk.IApplicationCredentialsSigning
  langs:
  - csharp
  - vb
  name: Use
  nameWithType: IApplicationCredentialsSigning.Use
  fullName: Okta.Sdk.IApplicationCredentialsSigning.Use
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Use
    path: ../src/Okta.Sdk/Generated/IApplicationCredentialsSigning.Generated.cs
    startLine: 25
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: ApplicationCredentialsSigningUse Use { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.ApplicationCredentialsSigningUse
    content.vb: Property Use As ApplicationCredentialsSigningUse
  overload: Okta.Sdk.IApplicationCredentialsSigning.Use*
  modifiers.csharp:
  - get
  - set
references:
- uid: Okta.Sdk
  commentId: N:Okta.Sdk
  name: Okta.Sdk
  nameWithType: Okta.Sdk
  fullName: Okta.Sdk
- uid: Okta.Sdk.IResource.Item(System.String)
  commentId: P:Okta.Sdk.IResource.Item(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: Item[String]
  nameWithType: IResource.Item[String]
  fullName: Okta.Sdk.IResource.Item[System.String]
  nameWithType.vb: IResource.Item(String)
  fullName.vb: Okta.Sdk.IResource.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetArrayProperty<T>(String)
  nameWithType: IResource.GetArrayProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetArrayProperty<T>(System.String)
  nameWithType.vb: IResource.GetArrayProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetArrayProperty(Of T)(System.String)
  name.vb: GetArrayProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty<T>
    nameWithType: IResource.GetArrayProperty<T>
    fullName: Okta.Sdk.IResource.GetArrayProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty(Of T)
    nameWithType: IResource.GetArrayProperty(Of T)
    fullName: Okta.Sdk.IResource.GetArrayProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetData
  commentId: M:Okta.Sdk.IResource.GetData
  parent: Okta.Sdk.IResource
  name: GetData()
  nameWithType: IResource.GetData()
  fullName: Okta.Sdk.IResource.GetData()
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  commentId: M:Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: SetProperty(String, Object)
  nameWithType: IResource.SetProperty(String, Object)
  fullName: Okta.Sdk.IResource.SetProperty(System.String, System.Object)
  spec.csharp:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetProperty<T>(String)
  nameWithType: IResource.GetProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetProperty<T>(System.String)
  nameWithType.vb: IResource.GetProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetProperty(Of T)(System.String)
  name.vb: GetProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty<T>
    nameWithType: IResource.GetProperty<T>
    fullName: Okta.Sdk.IResource.GetProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty(Of T)
    nameWithType: IResource.GetProperty(Of T)
    fullName: Okta.Sdk.IResource.GetProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource
  commentId: T:Okta.Sdk.IResource
  parent: Okta.Sdk
  name: IResource
  nameWithType: IResource
  fullName: Okta.Sdk.IResource
- uid: Okta.Sdk.IApplicationCredentialsSigning.Kid*
  commentId: Overload:Okta.Sdk.IApplicationCredentialsSigning.Kid
  name: Kid
  nameWithType: IApplicationCredentialsSigning.Kid
  fullName: Okta.Sdk.IApplicationCredentialsSigning.Kid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Okta.Sdk.IApplicationCredentialsSigning.LastRotated*
  commentId: Overload:Okta.Sdk.IApplicationCredentialsSigning.LastRotated
  name: LastRotated
  nameWithType: IApplicationCredentialsSigning.LastRotated
  fullName: Okta.Sdk.IApplicationCredentialsSigning.LastRotated
- uid: System.Nullable{System.DateTimeOffset}
  commentId: T:System.Nullable{System.DateTimeOffset}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTimeOffset>
  nameWithType: Nullable<DateTimeOffset>
  fullName: System.Nullable<System.DateTimeOffset>
  nameWithType.vb: Nullable(Of DateTimeOffset)
  fullName.vb: System.Nullable(Of System.DateTimeOffset)
  name.vb: Nullable(Of DateTimeOffset)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.DateTimeOffset
    name: DateTimeOffset
    nameWithType: DateTimeOffset
    fullName: System.DateTimeOffset
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.DateTimeOffset
    name: DateTimeOffset
    nameWithType: DateTimeOffset
    fullName: System.DateTimeOffset
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IApplicationCredentialsSigning.NextRotation*
  commentId: Overload:Okta.Sdk.IApplicationCredentialsSigning.NextRotation
  name: NextRotation
  nameWithType: IApplicationCredentialsSigning.NextRotation
  fullName: Okta.Sdk.IApplicationCredentialsSigning.NextRotation
- uid: Okta.Sdk.IApplicationCredentialsSigning.RotationMode*
  commentId: Overload:Okta.Sdk.IApplicationCredentialsSigning.RotationMode
  name: RotationMode
  nameWithType: IApplicationCredentialsSigning.RotationMode
  fullName: Okta.Sdk.IApplicationCredentialsSigning.RotationMode
- uid: Okta.Sdk.IApplicationCredentialsSigning.Use*
  commentId: Overload:Okta.Sdk.IApplicationCredentialsSigning.Use
  name: Use
  nameWithType: IApplicationCredentialsSigning.Use
  fullName: Okta.Sdk.IApplicationCredentialsSigning.Use
- uid: Okta.Sdk.ApplicationCredentialsSigningUse
  commentId: T:Okta.Sdk.ApplicationCredentialsSigningUse
  parent: Okta.Sdk
  name: ApplicationCredentialsSigningUse
  nameWithType: ApplicationCredentialsSigningUse
  fullName: Okta.Sdk.ApplicationCredentialsSigningUse
