### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  commentId: T:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  id: IAuthorizationServerCredentialsSigningConfig
  parent: Okta.Sdk
  children:
  - Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid
  - Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated
  - Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation
  - Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode
  - Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use
  langs:
  - csharp
  - vb
  name: IAuthorizationServerCredentialsSigningConfig
  nameWithType: IAuthorizationServerCredentialsSigningConfig
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  type: Interface
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: IAuthorizationServerCredentialsSigningConfig
    path: ../src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: Represents a AuthorizationServerCredentialsSigningConfig resource in the Okta API.
  example: []
  syntax:
    content: 'public interface IAuthorizationServerCredentialsSigningConfig : IResource'
    content.vb: >-
      Public Interface IAuthorizationServerCredentialsSigningConfig

          Inherits IResource
  inheritedMembers:
  - Okta.Sdk.IResource.Item(System.String)
  - Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  - Okta.Sdk.IResource.GetData
  - Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  - Okta.Sdk.IResource.GetProperty``1(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid
  commentId: P:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid
  id: Kid
  parent: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  langs:
  - csharp
  - vb
  name: Kid
  nameWithType: IAuthorizationServerCredentialsSigningConfig.Kid
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Kid
    path: ../src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
    startLine: 17
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: string Kid { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Kid As String
  overload: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated
  commentId: P:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated
  id: LastRotated
  parent: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  langs:
  - csharp
  - vb
  name: LastRotated
  nameWithType: IAuthorizationServerCredentialsSigningConfig.LastRotated
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: LastRotated
    path: ../src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
    startLine: 19
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: DateTimeOffset? LastRotated { get; }
    parameters: []
    return:
      type: System.Nullable{System.DateTimeOffset}
    content.vb: ReadOnly Property LastRotated As DateTimeOffset?
  overload: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation
  commentId: P:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation
  id: NextRotation
  parent: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  langs:
  - csharp
  - vb
  name: NextRotation
  nameWithType: IAuthorizationServerCredentialsSigningConfig.NextRotation
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: NextRotation
    path: ../src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
    startLine: 21
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: DateTimeOffset? NextRotation { get; }
    parameters: []
    return:
      type: System.Nullable{System.DateTimeOffset}
    content.vb: ReadOnly Property NextRotation As DateTimeOffset?
  overload: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode
  commentId: P:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode
  id: RotationMode
  parent: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  langs:
  - csharp
  - vb
  name: RotationMode
  nameWithType: IAuthorizationServerCredentialsSigningConfig.RotationMode
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: RotationMode
    path: ../src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
    startLine: 23
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: AuthorizationServerCredentialsRotationMode RotationMode { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.AuthorizationServerCredentialsRotationMode
    content.vb: Property RotationMode As AuthorizationServerCredentialsRotationMode
  overload: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use
  commentId: P:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use
  id: Use
  parent: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig
  langs:
  - csharp
  - vb
  name: Use
  nameWithType: IAuthorizationServerCredentialsSigningConfig.Use
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Use
    path: ../src/Okta.Sdk/Generated/IAuthorizationServerCredentialsSigningConfig.Generated.cs
    startLine: 25
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: AuthorizationServerCredentialsUse Use { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.AuthorizationServerCredentialsUse
    content.vb: Property Use As AuthorizationServerCredentialsUse
  overload: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use*
  modifiers.csharp:
  - get
  - set
references:
- uid: Okta.Sdk
  commentId: N:Okta.Sdk
  name: Okta.Sdk
  nameWithType: Okta.Sdk
  fullName: Okta.Sdk
- uid: Okta.Sdk.IResource.Item(System.String)
  commentId: P:Okta.Sdk.IResource.Item(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: Item[String]
  nameWithType: IResource.Item[String]
  fullName: Okta.Sdk.IResource.Item[System.String]
  nameWithType.vb: IResource.Item(String)
  fullName.vb: Okta.Sdk.IResource.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetArrayProperty<T>(String)
  nameWithType: IResource.GetArrayProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetArrayProperty<T>(System.String)
  nameWithType.vb: IResource.GetArrayProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetArrayProperty(Of T)(System.String)
  name.vb: GetArrayProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty<T>
    nameWithType: IResource.GetArrayProperty<T>
    fullName: Okta.Sdk.IResource.GetArrayProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty(Of T)
    nameWithType: IResource.GetArrayProperty(Of T)
    fullName: Okta.Sdk.IResource.GetArrayProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetData
  commentId: M:Okta.Sdk.IResource.GetData
  parent: Okta.Sdk.IResource
  name: GetData()
  nameWithType: IResource.GetData()
  fullName: Okta.Sdk.IResource.GetData()
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  commentId: M:Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: SetProperty(String, Object)
  nameWithType: IResource.SetProperty(String, Object)
  fullName: Okta.Sdk.IResource.SetProperty(System.String, System.Object)
  spec.csharp:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetProperty<T>(String)
  nameWithType: IResource.GetProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetProperty<T>(System.String)
  nameWithType.vb: IResource.GetProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetProperty(Of T)(System.String)
  name.vb: GetProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty<T>
    nameWithType: IResource.GetProperty<T>
    fullName: Okta.Sdk.IResource.GetProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty(Of T)
    nameWithType: IResource.GetProperty(Of T)
    fullName: Okta.Sdk.IResource.GetProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource
  commentId: T:Okta.Sdk.IResource
  parent: Okta.Sdk
  name: IResource
  nameWithType: IResource
  fullName: Okta.Sdk.IResource
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid*
  commentId: Overload:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid
  name: Kid
  nameWithType: IAuthorizationServerCredentialsSigningConfig.Kid
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Kid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated*
  commentId: Overload:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated
  name: LastRotated
  nameWithType: IAuthorizationServerCredentialsSigningConfig.LastRotated
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.LastRotated
- uid: System.Nullable{System.DateTimeOffset}
  commentId: T:System.Nullable{System.DateTimeOffset}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTimeOffset>
  nameWithType: Nullable<DateTimeOffset>
  fullName: System.Nullable<System.DateTimeOffset>
  nameWithType.vb: Nullable(Of DateTimeOffset)
  fullName.vb: System.Nullable(Of System.DateTimeOffset)
  name.vb: Nullable(Of DateTimeOffset)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.DateTimeOffset
    name: DateTimeOffset
    nameWithType: DateTimeOffset
    fullName: System.DateTimeOffset
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.DateTimeOffset
    name: DateTimeOffset
    nameWithType: DateTimeOffset
    fullName: System.DateTimeOffset
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation*
  commentId: Overload:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation
  name: NextRotation
  nameWithType: IAuthorizationServerCredentialsSigningConfig.NextRotation
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.NextRotation
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode*
  commentId: Overload:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode
  name: RotationMode
  nameWithType: IAuthorizationServerCredentialsSigningConfig.RotationMode
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.RotationMode
- uid: Okta.Sdk.AuthorizationServerCredentialsRotationMode
  commentId: T:Okta.Sdk.AuthorizationServerCredentialsRotationMode
  parent: Okta.Sdk
  name: AuthorizationServerCredentialsRotationMode
  nameWithType: AuthorizationServerCredentialsRotationMode
  fullName: Okta.Sdk.AuthorizationServerCredentialsRotationMode
- uid: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use*
  commentId: Overload:Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use
  name: Use
  nameWithType: IAuthorizationServerCredentialsSigningConfig.Use
  fullName: Okta.Sdk.IAuthorizationServerCredentialsSigningConfig.Use
- uid: Okta.Sdk.AuthorizationServerCredentialsUse
  commentId: T:Okta.Sdk.AuthorizationServerCredentialsUse
  parent: Okta.Sdk
  name: AuthorizationServerCredentialsUse
  nameWithType: AuthorizationServerCredentialsUse
  fullName: Okta.Sdk.AuthorizationServerCredentialsUse
