### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.Configuration.AuthorizationMode
  commentId: T:Okta.Sdk.Configuration.AuthorizationMode
  id: AuthorizationMode
  parent: Okta.Sdk.Configuration
  children:
  - Okta.Sdk.Configuration.AuthorizationMode.BearerToken
  - Okta.Sdk.Configuration.AuthorizationMode.PrivateKey
  - Okta.Sdk.Configuration.AuthorizationMode.SSWS
  langs:
  - csharp
  - vb
  name: AuthorizationMode
  nameWithType: AuthorizationMode
  fullName: Okta.Sdk.Configuration.AuthorizationMode
  type: Enum
  source:
    remote:
      path: src/Okta.Sdk/Configuration/AuthorizationMode.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: AuthorizationMode
    path: ../src/Okta.Sdk/Configuration/AuthorizationMode.cs
    startLine: 10
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk.Configuration
  summary: "\nAuthorization mode enum.\n"
  example: []
  syntax:
    content: public enum AuthorizationMode
    content.vb: Public Enum AuthorizationMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Okta.Sdk.Configuration.AuthorizationMode.SSWS
  commentId: F:Okta.Sdk.Configuration.AuthorizationMode.SSWS
  id: SSWS
  parent: Okta.Sdk.Configuration.AuthorizationMode
  langs:
  - csharp
  - vb
  name: SSWS
  nameWithType: AuthorizationMode.SSWS
  fullName: Okta.Sdk.Configuration.AuthorizationMode.SSWS
  type: Field
  source:
    remote:
      path: src/Okta.Sdk/Configuration/AuthorizationMode.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: SSWS
    path: ../src/Okta.Sdk/Configuration/AuthorizationMode.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk.Configuration
  summary: "\nIndicates that the SDK will send a SSWS token in the authorization header when making calls.\n"
  example: []
  syntax:
    content: SSWS = 0
    return:
      type: Okta.Sdk.Configuration.AuthorizationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Okta.Sdk.Configuration.AuthorizationMode.PrivateKey
  commentId: F:Okta.Sdk.Configuration.AuthorizationMode.PrivateKey
  id: PrivateKey
  parent: Okta.Sdk.Configuration.AuthorizationMode
  langs:
  - csharp
  - vb
  name: PrivateKey
  nameWithType: AuthorizationMode.PrivateKey
  fullName: Okta.Sdk.Configuration.AuthorizationMode.PrivateKey
  type: Field
  source:
    remote:
      path: src/Okta.Sdk/Configuration/AuthorizationMode.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: PrivateKey
    path: ../src/Okta.Sdk/Configuration/AuthorizationMode.cs
    startLine: 20
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk.Configuration
  summary: "\nIndicates that the SDK will request and send an access token in the authorization header when making calls.\n"
  example: []
  syntax:
    content: PrivateKey = 1
    return:
      type: Okta.Sdk.Configuration.AuthorizationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Okta.Sdk.Configuration.AuthorizationMode.BearerToken
  commentId: F:Okta.Sdk.Configuration.AuthorizationMode.BearerToken
  id: BearerToken
  parent: Okta.Sdk.Configuration.AuthorizationMode
  langs:
  - csharp
  - vb
  name: BearerToken
  nameWithType: AuthorizationMode.BearerToken
  fullName: Okta.Sdk.Configuration.AuthorizationMode.BearerToken
  type: Field
  source:
    remote:
      path: src/Okta.Sdk/Configuration/AuthorizationMode.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: BearerToken
    path: ../src/Okta.Sdk/Configuration/AuthorizationMode.cs
    startLine: 25
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk.Configuration
  summary: "\nIndicates that the SDK will use the provided access token <xref href=\"Okta.Sdk.Configuration.OktaClientConfiguration.BearerToken\" data-throw-if-not-resolved=\"false\"></xref> when making calls.\n"
  example: []
  syntax:
    content: BearerToken = 2
    return:
      type: Okta.Sdk.Configuration.AuthorizationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Okta.Sdk.Configuration
  commentId: N:Okta.Sdk.Configuration
  name: Okta.Sdk.Configuration
  nameWithType: Okta.Sdk.Configuration
  fullName: Okta.Sdk.Configuration
- uid: Okta.Sdk.Configuration.AuthorizationMode
  commentId: T:Okta.Sdk.Configuration.AuthorizationMode
  parent: Okta.Sdk.Configuration
  name: AuthorizationMode
  nameWithType: AuthorizationMode
  fullName: Okta.Sdk.Configuration.AuthorizationMode
- uid: Okta.Sdk.Configuration.OktaClientConfiguration.BearerToken
  commentId: P:Okta.Sdk.Configuration.OktaClientConfiguration.BearerToken
  isExternal: true
