### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.Configuration
  commentId: N:Okta.Sdk.Configuration
  id: Okta.Sdk.Configuration
  children:
  - Okta.Sdk.Configuration.AuthorizationMode
  - Okta.Sdk.Configuration.JsonWebKeyConfiguration
  - Okta.Sdk.Configuration.OktaClientConfiguration
  - Okta.Sdk.Configuration.ProxyConfiguration
  langs:
  - csharp
  - vb
  name: Okta.Sdk.Configuration
  nameWithType: Okta.Sdk.Configuration
  fullName: Okta.Sdk.Configuration
  type: Namespace
  assemblies:
  - Okta.Sdk
references:
- uid: Okta.Sdk.Configuration.AuthorizationMode
  commentId: T:Okta.Sdk.Configuration.AuthorizationMode
  parent: Okta.Sdk.Configuration
  name: AuthorizationMode
  nameWithType: AuthorizationMode
  fullName: Okta.Sdk.Configuration.AuthorizationMode
- uid: Okta.Sdk.Configuration.JsonWebKeyConfiguration
  commentId: T:Okta.Sdk.Configuration.JsonWebKeyConfiguration
  parent: Okta.Sdk.Configuration
  name: JsonWebKeyConfiguration
  nameWithType: JsonWebKeyConfiguration
  fullName: Okta.Sdk.Configuration.JsonWebKeyConfiguration
- uid: Okta.Sdk.Configuration.OktaClientConfiguration
  commentId: T:Okta.Sdk.Configuration.OktaClientConfiguration
  parent: Okta.Sdk.Configuration
  name: OktaClientConfiguration
  nameWithType: OktaClientConfiguration
  fullName: Okta.Sdk.Configuration.OktaClientConfiguration
- uid: Okta.Sdk.Configuration.ProxyConfiguration
  commentId: T:Okta.Sdk.Configuration.ProxyConfiguration
  parent: Okta.Sdk.Configuration
  name: ProxyConfiguration
  nameWithType: ProxyConfiguration
  fullName: Okta.Sdk.Configuration.ProxyConfiguration
- uid: Okta.Sdk.Configuration
  commentId: N:Okta.Sdk.Configuration
  name: Okta.Sdk.Configuration
  nameWithType: Okta.Sdk.Configuration
  fullName: Okta.Sdk.Configuration
