### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.IOAuthApplicationCredentials
  commentId: T:Okta.Sdk.IOAuthApplicationCredentials
  id: IOAuthApplicationCredentials
  parent: Okta.Sdk
  children:
  - Okta.Sdk.IOAuthApplicationCredentials.OauthClient
  langs:
  - csharp
  - vb
  name: IOAuthApplicationCredentials
  nameWithType: IOAuthApplicationCredentials
  fullName: Okta.Sdk.IOAuthApplicationCredentials
  type: Interface
  source:
    remote:
      path: src/Okta.Sdk/Generated/IOAuthApplicationCredentials.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: IOAuthApplicationCredentials
    path: ../src/Okta.Sdk/Generated/IOAuthApplicationCredentials.Generated.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: Represents a OAuthApplicationCredentials resource in the Okta API.
  example: []
  syntax:
    content: 'public interface IOAuthApplicationCredentials : IApplicationCredentials, IResource'
    content.vb: >-
      Public Interface IOAuthApplicationCredentials

          Inherits IApplicationCredentials
  inheritedMembers:
  - Okta.Sdk.IApplicationCredentials.Signing
  - Okta.Sdk.IApplicationCredentials.UserNameTemplate
  - Okta.Sdk.IResource.Item(System.String)
  - Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  - Okta.Sdk.IResource.GetData
  - Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  - Okta.Sdk.IResource.GetProperty``1(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Okta.Sdk.IOAuthApplicationCredentials.OauthClient
  commentId: P:Okta.Sdk.IOAuthApplicationCredentials.OauthClient
  id: OauthClient
  parent: Okta.Sdk.IOAuthApplicationCredentials
  langs:
  - csharp
  - vb
  name: OauthClient
  nameWithType: IOAuthApplicationCredentials.OauthClient
  fullName: Okta.Sdk.IOAuthApplicationCredentials.OauthClient
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IOAuthApplicationCredentials.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: OauthClient
    path: ../src/Okta.Sdk/Generated/IOAuthApplicationCredentials.Generated.cs
    startLine: 17
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: IApplicationCredentialsOAuthClient OauthClient { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.IApplicationCredentialsOAuthClient
    content.vb: Property OauthClient As IApplicationCredentialsOAuthClient
  overload: Okta.Sdk.IOAuthApplicationCredentials.OauthClient*
  modifiers.csharp:
  - get
  - set
references:
- uid: Okta.Sdk
  commentId: N:Okta.Sdk
  name: Okta.Sdk
  nameWithType: Okta.Sdk
  fullName: Okta.Sdk
- uid: Okta.Sdk.IApplicationCredentials.Signing
  commentId: P:Okta.Sdk.IApplicationCredentials.Signing
  parent: Okta.Sdk.IApplicationCredentials
  name: Signing
  nameWithType: IApplicationCredentials.Signing
  fullName: Okta.Sdk.IApplicationCredentials.Signing
- uid: Okta.Sdk.IApplicationCredentials.UserNameTemplate
  commentId: P:Okta.Sdk.IApplicationCredentials.UserNameTemplate
  parent: Okta.Sdk.IApplicationCredentials
  name: UserNameTemplate
  nameWithType: IApplicationCredentials.UserNameTemplate
  fullName: Okta.Sdk.IApplicationCredentials.UserNameTemplate
- uid: Okta.Sdk.IResource.Item(System.String)
  commentId: P:Okta.Sdk.IResource.Item(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: Item[String]
  nameWithType: IResource.Item[String]
  fullName: Okta.Sdk.IResource.Item[System.String]
  nameWithType.vb: IResource.Item(String)
  fullName.vb: Okta.Sdk.IResource.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetArrayProperty<T>(String)
  nameWithType: IResource.GetArrayProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetArrayProperty<T>(System.String)
  nameWithType.vb: IResource.GetArrayProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetArrayProperty(Of T)(System.String)
  name.vb: GetArrayProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty<T>
    nameWithType: IResource.GetArrayProperty<T>
    fullName: Okta.Sdk.IResource.GetArrayProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty(Of T)
    nameWithType: IResource.GetArrayProperty(Of T)
    fullName: Okta.Sdk.IResource.GetArrayProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetData
  commentId: M:Okta.Sdk.IResource.GetData
  parent: Okta.Sdk.IResource
  name: GetData()
  nameWithType: IResource.GetData()
  fullName: Okta.Sdk.IResource.GetData()
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  commentId: M:Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: SetProperty(String, Object)
  nameWithType: IResource.SetProperty(String, Object)
  fullName: Okta.Sdk.IResource.SetProperty(System.String, System.Object)
  spec.csharp:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetProperty<T>(String)
  nameWithType: IResource.GetProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetProperty<T>(System.String)
  nameWithType.vb: IResource.GetProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetProperty(Of T)(System.String)
  name.vb: GetProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty<T>
    nameWithType: IResource.GetProperty<T>
    fullName: Okta.Sdk.IResource.GetProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty(Of T)
    nameWithType: IResource.GetProperty(Of T)
    fullName: Okta.Sdk.IResource.GetProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IApplicationCredentials
  commentId: T:Okta.Sdk.IApplicationCredentials
  parent: Okta.Sdk
  name: IApplicationCredentials
  nameWithType: IApplicationCredentials
  fullName: Okta.Sdk.IApplicationCredentials
- uid: Okta.Sdk.IResource
  commentId: T:Okta.Sdk.IResource
  parent: Okta.Sdk
  name: IResource
  nameWithType: IResource
  fullName: Okta.Sdk.IResource
- uid: Okta.Sdk.IOAuthApplicationCredentials.OauthClient*
  commentId: Overload:Okta.Sdk.IOAuthApplicationCredentials.OauthClient
  name: OauthClient
  nameWithType: IOAuthApplicationCredentials.OauthClient
  fullName: Okta.Sdk.IOAuthApplicationCredentials.OauthClient
- uid: Okta.Sdk.IApplicationCredentialsOAuthClient
  commentId: T:Okta.Sdk.IApplicationCredentialsOAuthClient
  parent: Okta.Sdk
  name: IApplicationCredentialsOAuthClient
  nameWithType: IApplicationCredentialsOAuthClient
  fullName: Okta.Sdk.IApplicationCredentialsOAuthClient
