### YamlMime:ManagedReference
items:
- uid: Okta.Sdk.IPasswordPolicySettings
  commentId: T:Okta.Sdk.IPasswordPolicySettings
  id: IPasswordPolicySettings
  parent: Okta.Sdk
  children:
  - Okta.Sdk.IPasswordPolicySettings.Delegation
  - Okta.Sdk.IPasswordPolicySettings.Password
  - Okta.Sdk.IPasswordPolicySettings.Recovery
  langs:
  - csharp
  - vb
  name: IPasswordPolicySettings
  nameWithType: IPasswordPolicySettings
  fullName: Okta.Sdk.IPasswordPolicySettings
  type: Interface
  source:
    remote:
      path: src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: IPasswordPolicySettings
    path: ../src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
    startLine: 15
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  summary: Represents a PasswordPolicySettings resource in the Okta API.
  example: []
  syntax:
    content: 'public interface IPasswordPolicySettings : IResource'
    content.vb: >-
      Public Interface IPasswordPolicySettings

          Inherits IResource
  inheritedMembers:
  - Okta.Sdk.IResource.Item(System.String)
  - Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  - Okta.Sdk.IResource.GetData
  - Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  - Okta.Sdk.IResource.GetProperty``1(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Okta.Sdk.IPasswordPolicySettings.Delegation
  commentId: P:Okta.Sdk.IPasswordPolicySettings.Delegation
  id: Delegation
  parent: Okta.Sdk.IPasswordPolicySettings
  langs:
  - csharp
  - vb
  name: Delegation
  nameWithType: IPasswordPolicySettings.Delegation
  fullName: Okta.Sdk.IPasswordPolicySettings.Delegation
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Delegation
    path: ../src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
    startLine: 17
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: IPasswordPolicyDelegationSettings Delegation { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.IPasswordPolicyDelegationSettings
    content.vb: Property Delegation As IPasswordPolicyDelegationSettings
  overload: Okta.Sdk.IPasswordPolicySettings.Delegation*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IPasswordPolicySettings.Password
  commentId: P:Okta.Sdk.IPasswordPolicySettings.Password
  id: Password
  parent: Okta.Sdk.IPasswordPolicySettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: IPasswordPolicySettings.Password
  fullName: Okta.Sdk.IPasswordPolicySettings.Password
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Password
    path: ../src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
    startLine: 19
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: IPasswordPolicyPasswordSettings Password { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.IPasswordPolicyPasswordSettings
    content.vb: Property Password As IPasswordPolicyPasswordSettings
  overload: Okta.Sdk.IPasswordPolicySettings.Password*
  modifiers.csharp:
  - get
  - set
- uid: Okta.Sdk.IPasswordPolicySettings.Recovery
  commentId: P:Okta.Sdk.IPasswordPolicySettings.Recovery
  id: Recovery
  parent: Okta.Sdk.IPasswordPolicySettings
  langs:
  - csharp
  - vb
  name: Recovery
  nameWithType: IPasswordPolicySettings.Recovery
  fullName: Okta.Sdk.IPasswordPolicySettings.Recovery
  type: Property
  source:
    remote:
      path: src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
      branch: lr-docfx-gh-actions
      repo: https://github.com/okta/okta-sdk-dotnet.git
    id: Recovery
    path: ../src/Okta.Sdk/Generated/IPasswordPolicySettings.Generated.cs
    startLine: 21
  assemblies:
  - Okta.Sdk
  namespace: Okta.Sdk
  syntax:
    content: IPasswordPolicyRecoverySettings Recovery { get; set; }
    parameters: []
    return:
      type: Okta.Sdk.IPasswordPolicyRecoverySettings
    content.vb: Property Recovery As IPasswordPolicyRecoverySettings
  overload: Okta.Sdk.IPasswordPolicySettings.Recovery*
  modifiers.csharp:
  - get
  - set
references:
- uid: Okta.Sdk
  commentId: N:Okta.Sdk
  name: Okta.Sdk
  nameWithType: Okta.Sdk
  fullName: Okta.Sdk
- uid: Okta.Sdk.IResource.Item(System.String)
  commentId: P:Okta.Sdk.IResource.Item(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: Item[String]
  nameWithType: IResource.Item[String]
  fullName: Okta.Sdk.IResource.Item[System.String]
  nameWithType.vb: IResource.Item(String)
  fullName.vb: Okta.Sdk.IResource.Item(System.String)
  name.vb: Item(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: '['
    nameWithType: '['
    fullName: '['
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ']'
    nameWithType: ']'
    fullName: ']'
  spec.vb:
  - uid: Okta.Sdk.IResource.Item(System.String)
    name: Item
    nameWithType: IResource.Item
    fullName: Okta.Sdk.IResource.Item
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetArrayProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetArrayProperty<T>(String)
  nameWithType: IResource.GetArrayProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetArrayProperty<T>(System.String)
  nameWithType.vb: IResource.GetArrayProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetArrayProperty(Of T)(System.String)
  name.vb: GetArrayProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty<T>
    nameWithType: IResource.GetArrayProperty<T>
    fullName: Okta.Sdk.IResource.GetArrayProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetArrayProperty``1(System.String)
    name: GetArrayProperty(Of T)
    nameWithType: IResource.GetArrayProperty(Of T)
    fullName: Okta.Sdk.IResource.GetArrayProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetData
  commentId: M:Okta.Sdk.IResource.GetData
  parent: Okta.Sdk.IResource
  name: GetData()
  nameWithType: IResource.GetData()
  fullName: Okta.Sdk.IResource.GetData()
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetData
    name: GetData
    nameWithType: IResource.GetData
    fullName: Okta.Sdk.IResource.GetData
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  commentId: M:Okta.Sdk.IResource.SetProperty(System.String,System.Object)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: SetProperty(String, Object)
  nameWithType: IResource.SetProperty(String, Object)
  fullName: Okta.Sdk.IResource.SetProperty(System.String, System.Object)
  spec.csharp:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.SetProperty(System.String,System.Object)
    name: SetProperty
    nameWithType: IResource.SetProperty
    fullName: Okta.Sdk.IResource.SetProperty
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource.GetProperty``1(System.String)
  commentId: M:Okta.Sdk.IResource.GetProperty``1(System.String)
  parent: Okta.Sdk.IResource
  isExternal: true
  name: GetProperty<T>(String)
  nameWithType: IResource.GetProperty<T>(String)
  fullName: Okta.Sdk.IResource.GetProperty<T>(System.String)
  nameWithType.vb: IResource.GetProperty(Of T)(String)
  fullName.vb: Okta.Sdk.IResource.GetProperty(Of T)(System.String)
  name.vb: GetProperty(Of T)(String)
  spec.csharp:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty<T>
    nameWithType: IResource.GetProperty<T>
    fullName: Okta.Sdk.IResource.GetProperty<T>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Okta.Sdk.IResource.GetProperty``1(System.String)
    name: GetProperty(Of T)
    nameWithType: IResource.GetProperty(Of T)
    fullName: Okta.Sdk.IResource.GetProperty(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Okta.Sdk.IResource
  commentId: T:Okta.Sdk.IResource
  parent: Okta.Sdk
  name: IResource
  nameWithType: IResource
  fullName: Okta.Sdk.IResource
- uid: Okta.Sdk.IPasswordPolicySettings.Delegation*
  commentId: Overload:Okta.Sdk.IPasswordPolicySettings.Delegation
  name: Delegation
  nameWithType: IPasswordPolicySettings.Delegation
  fullName: Okta.Sdk.IPasswordPolicySettings.Delegation
- uid: Okta.Sdk.IPasswordPolicyDelegationSettings
  commentId: T:Okta.Sdk.IPasswordPolicyDelegationSettings
  parent: Okta.Sdk
  name: IPasswordPolicyDelegationSettings
  nameWithType: IPasswordPolicyDelegationSettings
  fullName: Okta.Sdk.IPasswordPolicyDelegationSettings
- uid: Okta.Sdk.IPasswordPolicySettings.Password*
  commentId: Overload:Okta.Sdk.IPasswordPolicySettings.Password
  name: Password
  nameWithType: IPasswordPolicySettings.Password
  fullName: Okta.Sdk.IPasswordPolicySettings.Password
- uid: Okta.Sdk.IPasswordPolicyPasswordSettings
  commentId: T:Okta.Sdk.IPasswordPolicyPasswordSettings
  parent: Okta.Sdk
  name: IPasswordPolicyPasswordSettings
  nameWithType: IPasswordPolicyPasswordSettings
  fullName: Okta.Sdk.IPasswordPolicyPasswordSettings
- uid: Okta.Sdk.IPasswordPolicySettings.Recovery*
  commentId: Overload:Okta.Sdk.IPasswordPolicySettings.Recovery
  name: Recovery
  nameWithType: IPasswordPolicySettings.Recovery
  fullName: Okta.Sdk.IPasswordPolicySettings.Recovery
- uid: Okta.Sdk.IPasswordPolicyRecoverySettings
  commentId: T:Okta.Sdk.IPasswordPolicyRecoverySettings
  parent: Okta.Sdk
  name: IPasswordPolicyRecoverySettings
  nameWithType: IPasswordPolicyRecoverySettings
  fullName: Okta.Sdk.IPasswordPolicyRecoverySettings
