name: DocFX Build and Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore src/Okta.Sdk
    
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      working-directory: docs
      continue-on-error: false
      with:
        args: docfx.json
    
    - name: List files tree after docs build
      run: ls

    - name: Deploy Docs to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        keep_files: true
    
