name: DocFX Build and Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
       args: install docfx --version=2.38.1
      #run: choco install --verbose docfx
    
    - name: Install dependencies
      run: dotnet restore src/Okta.Sdk
    
    - name: DocFx metadata
      working-directory: docs
      run: docfx metadata ./docfx.json -l Verbose
    
    - name: DocFX Build
      working-directory: docs
      run: docfx docfx.json --force
      continue-on-error: false
    
    - name: List files tree after docs build
      run: tree /f

    - name: Deploy Docs to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        keep_files: true
    
